#!/bin/bash

testCount=100
n=700
delta=1230

for i in 1 2 4 8
do
dest="delta_ms_for_par$i.csv"
touch $dest
cat /dev/null > $dest
command="./lab1-par-$i"
   for (( count=$testCount; count>0; count-- ))
   do
       for i in {0..10}
       do
           let "x =$n + $delta * $i"
           echo -e `$command $x` >> $dest
       done
   done
done

dest="delta_ms_for_par_clang.csv"
touch $dest
cat /dev/null > $dest
command="./lab1-par-clang"

for (( count=$testCount; count>0; count-- ))
do
for i in {0..10}
do
    let "x =$n + $delta * $i"
    echo -e `$command $x` >> $dest
done
done