#!/bin/bash

testCount=20
n=700
delta=1230

for thr in 1 2 4 8
do
dest="delta_ms_for_par_gcc$thr.csv"
touch $dest
cat /dev/null > $dest
command="./lab1-par-$thr"
   for (( count=$testCount; count>0; count-- ))
   do
       for i in {0..10}
       do
           let "x =$n + $delta * $i"
           echo -e `$command $x` >> $dest
       done
   done
done

dest="delta_ms_for_clang_with_vectorization.csv"
touch $dest
cat /dev/null > $dest
command="./lab1-par-clang"

for (( count=$testCount; count>0; count-- ))
do
for i in {0..10}
do
    let "x =$n + $delta * $i"
    echo -e `$command $x` >> $dest
done
done

dest="delta_ms_for_par_icc.csv"
touch $dest
cat /dev/null > $dest
command="./lab1_icc_par"
for (( count=$testCount; count>0; count-- ))
do
    for i in {0..10}
    do
        let "x = $n + $delta * $i"
        echo -e `$command $x` >> $dest
    done
done
